version: '3.4'
services:
  # mocklogin:
  #   image: lblod/mock-login-service:0.3.1
  identifier:
    restart: "no"
  dispatcher:
    restart: "no"
  virtuoso:
    restart: "no"
  database:
    restart: "no"
  resource:
    restart: "no"
  authentication:
    restart: "no"


