version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
      LOG_SESSION_ID: "true"
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.1
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  resource:
    image: semtech/mu-cl-resources:1.20.0
    links:
      - virtuoso:database
    volumes:
      - ./config/resources:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.4
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  authentication: 
    image: mu-node-authentication-service
    volumes:
      - /media/achraf/Main/projects/mu-semtech/mu-node-authentication-service:/app
    environment: 
      NODE_ENV: "development"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

